import ellipse1 from "./assets/Ellipse 1-1.png";
import ellipse2 from "./assets/Ellipse 1-2.png";
import ellipse3 from "./assets/Ellipse 1-3.png";
import ellipse4 from "./assets/Ellipse 1-4.png";
import ellipse5 from "./assets/Ellipse 1-5.png";
import ellipse6 from "./assets/Ellipse 1-6.png";
import ellipse7 from "./assets/Ellipse 1.png";
import ellipse8 from "./assets/Ellipse 2-1.png";
import ellipse9 from "./assets/Ellipse 2-2.png";
import ellipse10 from "./assets/Ellipse 2.png";
import ellipse11 from "./assets/Ellipse 3.png";

const TABLE_DATA = [
  {
    id: crypto.randomUUID(),
    checkBox: false,
    img: ellipse1,
    fullName: "John Smith",
    email: "john.smith@gmail.com",
    username: "jonny77",
    status: "Active",
    role: "Admin",
    joinedDate: "March 12, 2023",
    lastActive: "1 minute ago",
    actions: "",
  },
  {
    id: crypto.randomUUID(),
    checkBox: false,
    img: ellipse2,
    fullName: "Olivia Bennett",
    email: "ollyben@gmail.com",
    username: "olly659",
    status: "Inactive",
    role: "User",
    joinedDate: "June 27, 2022",
    lastActive: "1 month ago",
    actions: "",
  },
  {
    id: crypto.randomUUID(),
    checkBox: false,
    img: ellipse3,
    fullName: "Daniel Warren",
    email: "dwarren3@gmail.com",
    username: "dwarren3",
    status: "Banned",
    role: "User",
    joinedDate: "January 8, 2024",
    lastActive: "4 days ago",
    actions: "",
  },
  {
    id: crypto.randomUUID(),
    checkBox: false,
    img: ellipse4,
    fullName: "Chole Hayes",
    email: "chloehhye@gmail.com",
    username: "chloehh",
    status: "Pending",
    role: "Guest",
    joinedDate: "October 5, 2021",
    lastActive: "10 days ago",
    actions: "",
  },
  {
    id: crypto.randomUUID(),
    checkBox: false,
    img: ellipse5,
    fullName: "Marcus Reed",
    email: "reeds777@gmail.com",
    username: "reeds7",
    status: "Suspended",
    role: "User",
    joinedDate: "February 19, 2023",
    lastActive: "3 months ago",
    actions: "",
  },
  {
    id: crypto.randomUUID(),
    checkBox: false,
    img: ellipse6,
    fullName: "Isabelle Clark",
    email: "belleclark@gmail.com",
    username: "bellecl",
    status: "Active",
    role: "Moderator",
    joinedDate: "August 30, 2022",
    lastActive: "1 week ago",
    actions: "",
  },
  {
    id: crypto.randomUUID(),
    checkBox: false,
    img: ellipse7,
    fullName: "Lucas Mitchell",
    email: "lucamich@gmail.com",
    username: "lucamich",
    status: "Active",
    role: "Guest",
    joinedDate: "April 23, 2024",
    lastActive: "4 hours ago",
    actions: "",
  },
  {
    id: crypto.randomUUID(),
    checkBox: false,
    img: ellipse8,
    fullName: "Mark Wilburg",
    email: "markwill32@gmail.com",
    username: "markwill32",
    status: "Banned",
    role: "User",
    joinedDate: "November 14, 2020",
    lastActive: "2 months ago",
    actions: "",
  },
  {
    id: crypto.randomUUID(),
    checkBox: false,
    img: ellipse9,
    fullName: "Nicholas Agenn",
    email: "nicolass009@gmail.com",
    username: "nicolass009",
    status: "Suspended",
    role: "User",
    joinedDate: "July 6, 2023",
    lastActive: "3 hours ago",
    actions: "",
  },
  {
    id: crypto.randomUUID(),
    checkBox: false,
    img: ellipse10,
    fullName: "Mia Nadinn",
    email: "mianaddiin@gmail.com",
    username: "mianaddiin",
    status: "Inactive",
    role: "Guest",
    joinedDate: "December 31, 2021",
    lastActive: "4 months ago",
    actions: "",
  },
  {
    id: crypto.randomUUID(),
    checkBox: false,
    img: ellipse11,
    fullName: "Noemi Villan",
    email: "noemivill99@gmail.com",
    username: "noemi",
    status: "Active",
    role: "Admin",
    joinedDate: "August 10, 2024",
    lastActive: "15 minutes ago",
    actions: "",
  },
];
export default TABLE_DATA;
